/** @format */

import i18n from "i18next"
import { initReactI18next } from "react-i18next"

// the translations
// (tip move them in a JSON file and import them,
// or even better, manage them separated from your code: https://react.i18next.com/guides/multiple-translation-files)
const resources = {
  th: {
    translation: {
      "Username or email": "กรอกชื่อผู้ใช้ หรือ อีเมล",
      "Enter your password": "กรอกรหัสผ่าน",
      "Login now": "ลงชื่อเข้าใช้",
      "Visit Monitor Demo": "เดโมมอนิเตอร์",
      "Welcome to Your Monitoring":
        "ยินดีต้อนรับสู่การเฝ้าติดตามมอนิเตอร์ของคุณ",
      Monitor: "มอนิเตอร์",
      Report: "รายงานข้อมูล",
      Notification: "การแจ้งเตือน",
      User: "ผู้ใช้",
      "User Information": "ข้อมูลผู้ใช้",
      Username: "ชื่อผู้ใช้",
      "Birth Date": "วันเกิด",
      "Gender": "เพศ",
      "Phone Number": "เบอร์โทรศัพท์",
      "E-mail": "อีเมล",

       // Device
       "DeviceSpan1" : "อุปกรณ์ของฉัน",
       "DeviceSpan2" : "ชื่ออุปกรณ์",
       "DeviceSpan3" : "หมายเลขพินอุปกรณ์",
       "DeviceSpan4" : "โหลด",
       "DeviceSpan5" : "อินเวอเตอร์",
       "DeviceSpan6" : "แผงโซลาร์เซลล์",
       "DeviceSpan7" : "แบตเตอรี่",
       "DeviceSpan8" : "การไฟฟ้า",

      // Chart
      "ChartSpan1": "แผนภูมิพลังงาน",
      "ChartSpan2": "เลือกประเภท",
      "ChartSpan3": "วัน",
      "ChartSpan4": "เดือน",
      "ChartSpan5": "ปี",
      "ChartSpan6": "รวม",
      "ChartSpan7": "พลังงาน (kWh)",
      "ChartSpan8": "ชม",
      "ChartSpan9": "ค่าโหลดกำลังไฟฟ้าที่ใช้จริง",
      "ChartSpan10": "การผลิตไฟฟ้าโซลาร์เซลล์ ทั้งหมดในวันนั้น",
      "ChartSpan11": "วว-ดด-ปปปปป",
      "ChartSpan12": "ดด-ปปปป",
      "ChartSpan13": "ปปปป",
      "ChartSpan14": "ขยายเข้า",
      "ChartSpan15": "ขยายออก",
      "ChartSpan16": "ตั้งค่าอีกครั้ง",

      // Chart Power
      "ChartPSpan1": "พลังงานชาร์จ",
      "ChartPSpan2": "วันนี้",
      "ChartPSpan3": "กำลังไฟชาร์จ PV",
      "ChartPSpan4": "รายละเอียด",

      // Bill
      "BillSpan1": "ผลกำไรค่าไฟ",
      "BillSpan2": "ยูนิตที่ใช้",
      "BillSpan3": "ผลกำไรค่าไฟ",
      "BillSpan4": "บาท",
      "BillSpan5": "",
      //solar energy flow

      "Solar Energy Flow": "การไหลของพลังงาน",

      // popup load
      "Load percentage": "เปอร์เซ็นการใช้โหลด",
      "Load apparent power": "ค่าโหลดกำลังไฟฟ้าที่ปรากฎ",
      "Load active power": "ค่าโหลดกำลังไฟฟ้าที่ใช้จริง",
      "Output voltage": "ค่าแรงดันเอาท์พุต",
      "Output frequency": "ค่าความถี่เอาท์พุต",
      "Output current": "ค่ากระแสเอาท์พุต",
      "Output active power": "โหลดกำลังไฟฟ้าเอาท์พุตที่ใช้งาน",
      "Output apparent power": "ค่าโหลดกำลังไฟฟ้าเอาท์พุตที่ปรากฎ",
      "Total power output on the day": "ค่าพลังงานเอาท์พุตที่ใช้ทั้งหมดในวันนี้",
      // popup invert
      "Inverter voltage": "ค่าแรงดันของเครื่องอินเวอร์เตอร์",
      "Inverter frequency": "ค่าความถี่ของเครื่องอินเวอร์เตอร์",
      "Inverter current": "ค่ากระแสของเครื่องอินเวอร์เตอร์",
      // popup pv
      "Photovoltaic voltage": "ค่าแรงดันของโซลาร์เซลล์",
      "Photovoltaic charging current": "ค่ากระแสชาร์จไฟฟ้าของโซลาร์เซลล์",
      "Photovoltaic current": "ค่ากระแสไฟฟ้าของโซลาร์เซลล์ปัจจุบัน",
      "Total photovoltaic power": "พลังงานไฟฟ้าของโซลาร์เซลล์",
      "Total photovoltaic power generation on that day": "การผลิตไฟฟ้าโซลาร์เซลล์ทั้งหมดในวันนี้",
      "Total photovoltaic power generations": "การผลิตไฟฟ้าโซลาร์เซลล์ทั้งหมด",
      "Total photovoltaic power generation": "การผลิตไฟฟ้าโซลาร์เซลล์ทั้งหมด",
      // popup battery
      "Battery Voltage": "ค่าแรงดันแบตเตอรี่",
      "Battery Discharge Current": "ค่ากระแสไฟฟ้าขาออกจากแบตเตอรี่ที่จ่ายให้กับโหลด",
      "Charging Voltage": "ค่าแรงดันไฟฟ้าในการชาร์จ",
      "Number of Battery Cells": "จำนวนเซลล์แบตเตอรี่",
      "Charging Current": "ค่ากระแสการชาร์จ",
      "Charging Power": "กระแสไฟชาร์จ",
      "Battery Capacity (Battery SOC)": "ค่าความจุของแบตเตอรี่",
      "Battery Capacity Query": "รุ่นความจุของแบตเตอรี่",
      "Battery Current": "ค่ากระแสไฟฟ้าของแบตเตอรี่",
      // popup gird 
      "Grid Input voltage": "ค่าแรงดันไฟฟ้าเข้าอินเวอเตอร์",
      "Grid  Frequency": "ค่าความถี่ไฟฟ้าเข้าอินเวอเตอร์อินพุต",
      "Total power generated by the Grid on that day": "จำนวนไฟฟ้าที่ผลิตจากพลังงานโซลาร์เซลล์ทั้งหมดของวันนี้",
      "Total Grid power generation": "จำนวนไฟฟ้าที่ผลิตจากพลังงานโซลาร์เซลล์ทั้งหมด",
      "Grid voltage": "แรงดันไฟฟ้ากริด",
      "Grid frequency": "ค่าความถี่ไฟฟ้าเข้าอินเวอเตอร์อินพุต",
      "Grid current output": "เอาท์พุตกระแสกริด",
      "Output frequency": "ค่าความถี่เอาท์พุต"
    },
  },
  en: {
    translation: {
      "Username or email": "Username or email",
      "Enter your password": "Enter your password",
      "Login now": "Login now",
      "Visit Monitor Demo": "Visit Monitor Demo",
      "Welcome to Your Monitoring": "Welcome to Your Monitoring",
      Monitor: "Monitor",
      Report: "Report",
      Notification: "Notification",
      User: "User",
      "User Information": "User Information",
      Username: "Username",
      "Birth Date": "Birth Date",
      "Gender": "Gender",
      "Phone Number": "Phone Number",
      "E-mail": "E-mail",

      // Device
      "DeviceSpan1" : "My Device",
      "DeviceSpan2" : "Device Name",
      "DeviceSpan3" : "Device's PN",
      "DeviceSpan4" : "Load",
      "DeviceSpan5" : "Inverter",
      "DeviceSpan6" : "PV",
      "DeviceSpan7" : "Battery",
      "DeviceSpan8" : "Grid",

      // Chart
      "ChartSpan1": "Solar Power Chart",
      "ChartSpan2": "Selected Type",
      "ChartSpan3": "Day",
      "ChartSpan4": "Month",
      "ChartSpan5": "Years",
      "ChartSpan6": "Total",
      "ChartSpan7": "Power (kWh)",
      "ChartSpan8": "H",
      "ChartSpan9": "Current load power",
      "ChartSpan10": "PV power on the day",
      "ChartSpan11": "DD-MM-YYYY",
      "ChartSpan12": "MM-YYYY",
      "ChartSpan13": "YYYY",
      "ChartSpan14": "Zoom in",
      "ChartSpan15": "Zoom out",
      "ChartSpan16": "Reset",

      // Chart Power
      "ChartPSpan1": "Charge Power",
      "ChartPSpan2": "Today",
      "ChartPSpan3": "PV Charging Power",
      "ChartPSpan4": "System Details",

      // Bill
      "BillSpan1": "Earn Profit Energy Bill",
      "BillSpan2": "Unit",
      "BillSpan3": "Saved",
      "BillSpan4": "THB",
      "BillSpan5": "",
      // solar energy
      "Solar Energy Flow": "Solar Energy Flow",

      // popup flow load
      "Load percentage": "Load percentage ",
      "Load apparent power": "Load apparent power",
      "Load active power": "Load active power",
      "Output voltage": "Output voltage",
      "Output frequency": "Output frequency",
      "Output current": "Output current",
      "Output active power": "Output active power",
      "Output apparent power": "Output apparent power",
      "Total power output on the day": "Total power output on the day",
      // popup flow inverter
      "Inverter voltage": "Inverter voltage",
      "Inverter frequency": "Inverter frequency",
      "Inverter current": "Inverter current",
      // popup flow PV
      "Photovoltaic voltage": "Photovoltaic voltage",
      "Photovoltaic charging current": "Photovoltaic charging current",
      "Photovoltaic current": "Photovoltaic current",
      "Total photovoltaic power": "Total photovoltaic power",
      "Total photovoltaic power generation on that day": "Total photovoltaic power generation on that day",
      "Total photovoltaic power generations": "Total photovoltaic power generations",
      "Total photovoltaic power generation": "Total photovoltaic power generation",
      // popup flow battery
      "Battery Voltage": "Battery Voltage",
      "Battery Discharge Current": "Battery Discharge Current",
      "Charging Voltage": "Charging Voltage",
      "Number of Battery Cells": "Number of Battery Cells",
      "Charging Current": "Charging Current",
      "Charging Power": "Charging Power",
      "Battery Capacity (Battery SOC)": "Battery Capacity (Battery SOC)",
      "Battery Capacity Query": "Battery Capacity Query",
      "Battery Current": "Battery Current",
      // popup gird
      "Grid Input voltage": "Grid Input voltage",
      "Grid  Frequency": "Grid Frequency",
      "Total power generated by the Grid on that day": "Total power generated by the Grid on that day",
      "Total Grid power generation": "Total Grid power generation",
      "Grid voltage": "Grid voltage",
      "Grid frequency": "Grid frequency",
      "Grid current output": "Grid current output",
      "Output frequency": "Output frequency"
    },
  },
}

const getLang = localStorage.getItem('Language');

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    lng: getLang == "EN" ? "en" : "th",
    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  })

export default i18n
